# Generated by Django 3.1.7 on 2021-03-16 00:55

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210315_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtail.core.fields.StreamField([('title_text_block', wagtail.core.blocks.StructBlock([('title_text', wagtail.core.blocks.CharBlock(form_classname='title', required=True)), ('size', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], required=False))])), ('image_block', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.core.blocks.CharBlock(required=False))])), ('quote_block', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock(required=True)), ('attribute_name', wagtail.core.blocks.CharBlock(required=True))])), ('richtext_block', wagtail.core.blocks.RichTextBlock(icon='edit', label='RichText', template='base/blocks/richtext_block.html')), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='insert embed', template='base/blocks/embed_block.html'))], blank=True),
        ),
    ]
